server:
  port: 8401

spring:
  application:
    name: FEBS-Monitor-Admin
  security:
    user:
      name: febs
      password: 123456
  boot:
    admin:
      ui:
        title: ${spring.application.name}
